### ISSUE TITLE
Battery Usage

### ISSUE THREAD

**Issue by ay8s** [wwdc-family/app#44]
In the last 24 hours it's used 53%. Wonder if it might be better to use significant location changes in the run up to WWDC before switching out to more accurate location?

If it helps, my side project for location tracking for another event is native and cook possibly hook it up with the family DB. Although know you're wanting to check out React Native. 👍

**Comment by matthijs2704** [comment]
Are you sure you're running the latest version? As battery usage has been significantly improved in the last few betas... It's now hardly noticeable (definitely not as significant as 53%, which I also had in beta 54 or so)

Not sure about this one, but hooking that up would mean two apps to achieve the same result, right? Haha, and would kinda defeat the purpose of @KrauseFx's app :P

**Comment by ay8s** [comment]
Using 1.0 (60) so looks to be the latest at least in my TestFlight app.

Was thinking the native code would replace the React Native version if battery usage can't be improved rather than be seperate. Although I know @KrauseFx is using it to check out React Native.

**Comment by KrauseFx** [comment]
Mh, that should have been fixed... weird. Yeah, feel free to look into the project and see if you can improve it 👍  Having a less accurate location until WWDC starts sounds very reasonable to me

**Comment by ay8s** [comment]
Updating iOS to see if that improves things at all.

**Comment by matthijs2704** [comment]
Hmm weird! But having less accuracy before wwdc doesn't solve the problem and would mean that everyone at WWDC would have really bad battery life. Which could also mean that they will either turn off background location sharing or even delete the app

**Comment by ay8s** [comment]
Will see if the iOS update improves things, did see some issues around locationd reported by others in the forums and spotted that a bunch in my devices logs.

Changing it to significant location updates would improve it prior to WWDC but not during the conference, likely when battery life is needed most. Will see if I can spot anything, although not used React Native too much.

**Comment by ay8s** [comment]
Just to update, still seeing battery usage with the latest update to iOS and the app. https://cl.ly/2T0T151B0f2j

**Comment by stephensilber** [comment]
My guess as to why battery drain is high is due to the distance filter being set to `250m`. This is still keeping the GPS chip on constantly in the background. A better solution might be to rely on significant location updates more, and when that fires, ramp up the GPS chip until you get an accurate read, and then ramp it back down. Anything over 1km switches to cellular triangulation + wifi instead of keeping the GPS chip on, which has much lower battery consumption.

An alternative solution could involve adding a geofence once a user's location stops moving for a certain amount of time, and only ramping up GPS once they break out of that geofence. 

https://github.com/wwdc-family/app/blob/master/app/mapViewComponent.js#L224

**Comment by KrauseFx** [comment]
Sounds good to me @stephensilber 👍  If you have some free time, feel free to submit a PR improving the battery usage 🚀

**Comment by stephensilber** [comment]
Will try to put something together before the weekend 👍

**Comment by klaas** [comment]
Some info from a first time install yesterday:

I installed WWDC.family for the first time 17 hours ago and it drained my phone immediately. It seems to use battery in the airplane mode as well, because during the 16 hours in the background the airplane mode was turned on for about 7 hours.

![img_8437](https://cloud.githubusercontent.com/assets/320967/26675260/922afd8e-46c3-11e7-8964-dede49d5bdcf.PNG)

**Comment by stephensilber** [comment]
I was playing with this last night. Not sure I'm competent enough with React to get something useful together by this weekend. A simpler fix would be to only user `significant location updates`, which fires whenever a user moves 500m or more. This will make it a little less accurate, but maybe an option to toggle high accuracy in the settings would be a suitable workaround for now?
